"""add_explanation_fields_to_trust_reports

Revision ID: 28c5d86670f4
Revises: 08c9fd12b72b
Create Date: 2026-08-11 10:50:48.953531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28c5d86670f4'
down_revision: Union[str, None] = '08c9fd12b72b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trust_reports', sa.Column('explanation', sa.Text(), nullable=True))
    op.add_column('trust_reports', sa.Column('key_risks', sa.Text(), nullable=True))
    op.add_column('trust_reports', sa.Column('positive_signals', sa.Text(), nullable=True))
    op.add_column('trust_reports', sa.Column('recommendation', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trust_reports', 'recommendation')
    op.drop_column('trust_reports', 'positive_signals')
    op.drop_column('trust_reports', 'key_risks')
    op.drop_column('trust_reports', 'explanation')
    # ### end Alembic commands ###
