"""add_multi_risk_columns_to_trust_reports

Revision ID: ad7588b6a024
Revises: 4b0e2f3a5c6d
Create Date: 2026-09-01 22:23:13.563431

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad7588b6a024'
down_revision: Union[str, None] = '4b0e2f3a5c6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trust_reports', sa.Column('technical_trust_score', sa.Integer(), nullable=True))
    op.add_column('trust_reports', sa.Column('content_risk_score', sa.Integer(), nullable=True))
    op.add_column('trust_reports', sa.Column('reputation_risk_score', sa.Integer(), nullable=True))
    op.add_column('trust_reports', sa.Column('behavioral_risk_score', sa.Integer(), nullable=True))
    op.add_column('trust_reports', sa.Column('overall_risk_score', sa.Integer(), nullable=True))
    op.add_column('trust_reports', sa.Column('overall_risk_level', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='risklevel'), nullable=True))
    op.add_column('trust_reports', sa.Column('risk_factors', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trust_reports', 'risk_factors')
    op.drop_column('trust_reports', 'overall_risk_level')
    op.drop_column('trust_reports', 'overall_risk_score')
    op.drop_column('trust_reports', 'behavioral_risk_score')
    op.drop_column('trust_reports', 'reputation_risk_score')
    op.drop_column('trust_reports', 'content_risk_score')
    op.drop_column('trust_reports', 'technical_trust_score')
    # ### end Alembic commands ###
